### PR TITLE
Wordwrap on edit for title of workitem

### PR DESCRIPTION
**Pull request by SMahil**

### CODE REVIEW

**Comment by sanbornsen** [comment]
This doesn't fix the issue #283

**Comment by sanbornsen** [comment]
@naina-verma can you help @SMahil to understand the problem, so that she can fix it!!

**Comment by SMahil** [comment]
@sanbornsen this issue is not related to issue no 283. This is the different change

**Comment by sanbornsen** [comment]
@SMahil Your branch is named with 283. Well, if it's not then what doe sit fix?

**Comment by SMahil** [comment]
My bad... it is related to wordwrap fix only..: got confused in numbers.. its a css fix for that issue

**Comment by sanbornsen** [comment]
Okay, then getting back to the point, this doesn't fix the issue.

**Comment by SMahil** [comment]
The text will break down to another line if it is too long... if there is any other requirement let me know

**Comment by nimishamukherjee** [comment]
@SMahil ran your PR still issue seen. Use these steps to replicate issue.
Enter the below title:
Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14 Some Title 14

This is the screen
scrollissue

The page has a scrollbar and the detail's panel has a scrollbar.

On reviewing issue #283 these are the issues that need to be fixed:
- No character limit on title : based on previous conversation, we are not going to restrict the title.
- Due to long title of workitem display page goes to long scroll : this needs to be fixed and this is the issue that I have just mentioned.

**Comment by SMahil** [comment]
@nimishamukherjee  for me its coming fine on firefox. I have attached the screenshot for same
screen shot 2016-11-11 at 3 50 14 pm

**Comment by nimishamukherjee** [comment]
@SMahil did you try saving this title. Your screenshot is in edit mode. After saving the scroll comes.

**Comment by joshuawilson** [comment]
[test]

**Comment by SMahil** [comment]
Committed the fix...

**Comment by nimishamukherjee** [comment]
@sanbornsen can you check this PR and approve as you have given a review comment? @SMahil has fixed the issue. It works for me on Firefox.

**Comment by sanbornsen** [comment]
This issue is still there in Firefox mobile. Try a long title on mobile view of Firefox.

**Comment by SMahil** [comment]
@sanbornsen @nimishamukherjee I have fixed the issue for firefox mobile. Please review

**Comment by sanbornsen** [comment]
@SMahil @nimishamukherjee everything is looking good.

**Comment by sanbornsen** [comment]
@SMahil please update your branch.

**Pull request merged**
