### PR TITLE
Functional tests for WI states.

### PR DESCRIPTION
**Pull request by naina-verma**
Functional tests for WI States dropdown UI
- Verify how many state changes exists in drop down Mobile/Desktop
- Verify the name display of workitem state are correct Mobile/Desktop
- Verfify on selecting workitem state it should display in list and detail view both pages Mobile/Desktop

### CODE REVIEW

**Comment by naina-verma** [comment]
@ldimaggi , Hi i have updated this branch with WI state functional test cases , please review.
#321 is now closed.

**Comment by naina-verma** [comment]
@ldimaggi , i have updated thanks for review.

**Comment by joshuawilson** [comment]
[test]
@ldimaggi please review

**Comment by naina-verma** [comment]
@ldimaggi , can you please mention the method name at 142 line

**Comment by naina-verma** [comment]
@ldimaggi , done!

**Comment by joshuawilson** [comment]
[test]

**Comment by naina-verma** [comment]
@joshuawilson , rebased !

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
