### PR TITLE
Logout and login option in mobile view

### PR DESCRIPTION
**Pull request by sanbornsen**
- Added a new dropdown library
- Added a dropdown with a user icon on header fro mobile view

This PR will need a package reinstall. 
```
npm run reinstall
```

### CODE REVIEW

**Comment by sanbornsen** [comment]
[test]

**Comment by joshuawilson** [comment]
@sanbornsen please add a note to the description when you add a package that this PR needs "npm install" before trying it out.

**Comment by joshuawilson** [comment]
[test]

**Comment by sanbornsen** [comment]
[test]

**Comment by ppitonak** [comment]
This is related to issue #234, see my comment on that issue.

**Comment by joshuawilson** [comment]
@ppitonak I asked about the license and got approval.

**Pull request merged**
