### PR TITLE
Changed tsconfig to comply to new ts format (removed types).

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Fixes vscode warnings on that.

### CODE REVIEW

**Comment by joshuawilson** [comment]
@michaelkleinhenz This was added after we found out that some of the team was unable to install.  

@nimishamukherjee @sanbornsen @SMahil @naina-verma Can you please test this by doing the following: 
rm -rf node_modules 
rm -rf typings
npm cache clean
npm install

**Comment by michaelkleinhenz** [comment]
Mmmh..install works for me, but not running. It seems it does not install the typings.
I added the typings manually and with --save -G. It created a typings.json. Now everything is running again.

**Comment by michaelkleinhenz** [comment]
@all `typings install` is also required after `npm install`.

**Comment by joshuawilson** [comment]
@michaelkleinhenz The change TS 2 allows us to not need to install the typings anymore. So if you do that you are reverting back to TS1 way of things. Unless you have seen new guidance for TS2.

**Comment by michaelkleinhenz** [comment]
Ah, this gives a hint..

**Comment by michaelkleinhenz** [comment]
Found it. The missing info for me was that the typings was removed due to the new version. The vscode warnings are gone after a cleanroom npm install. Problems were caused by the old ts still hanging around.

**Pull request closed without merging**
