### PR TITLE
Functional tests for WI States dropdown UI

### PR DESCRIPTION
**Pull request by naina-verma**
Functional tests for WI States dropdown UI
    - Verify how many state changes exists in drop down Mobile/Desktop
    - Verify the name display of workitem state are correct Mobile/Desktop
    - Verfify on selecting workitem state it should display in list and detail view both pages Mobile/Desktop

### CODE REVIEW

**Comment by naina-verma** [comment]
@ldimaggi , please review !

**Comment by nimishamukherjee** [comment]
@naina-verma which editor are you using? Three of the files do not have any code changes, they only have spacing changes - protractor.config.js, chat.spec.js, and quickadd-workitem.spec.js.

**Comment by naina-verma** [comment]
@Nimisha , I am using Atom

On Thu, Nov 17, 2016 at 1:38 PM, Nimisha Mukherjee <notifications@github.com

**Comment by nimishamukherjee** [comment]
@naina-verma most of us are now using VS Code (https://code.visualstudio.com).

**Comment by joshuawilson** [comment]
[test]

**Comment by ldimaggi** [comment]
Naina - Aren't the changes in this PR the same as in: https://github.com/almighty/almighty-ui/pull/315 ?

**Comment by naina-verma** [comment]
@ldimaggi ,These tests belongs to Task  #316 
#315 PR belongs to Task #292

**Comment by joshuawilson** [comment]
If this is based on the commit in PR #315 then you have 2 options. Cancel #315 and have both of these committed or rebase the commit you want on top of master instead of the branch with #315.

**Pull request closed without merging**
