### PR TITLE
Move deploy image to nginx

### PR DESCRIPTION
**Pull request by aslakknutsen**
Based on nginx image for Openshift by KB:
https://github.com/kbsingh/openshift-nginx

### CODE REVIEW

**Comment by joshuawilson** [comment]
@aslakknutsen just to clarify, this is not ready to be merged yet.

**Comment by aslakknutsen** [comment]
Correct

**Comment by aslakknutsen** [comment]
[test]

**Comment by aslakknutsen** [comment]
[test]

**Pull request merged**
