### PR TITLE
In memory data item fixed to support functional tests

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by sanbornsen** [comment]
@joshuawilson @michaelkleinhenz Tests might fail on Jenkins but this needs to be merged

**Comment by joshuawilson** [comment]
I just ran this and it looks like the Functional tests need to be updated too.

**Comment by sanbornsen** [comment]
[test]

**Comment by sanbornsen** [comment]
test

**Comment by michaelkleinhenz** [comment]
@sanbornsen Yes, sorry, I forgot to mention this when we spoke about it. The test expects the "empty" titles right now, you have to change the expects in the test specs too.

**Comment by sanbornsen** [comment]
@michaelkleinhenz yeah, we have everything in place in this PR.

**Pull request merged**
