### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by gobindaakhuli**
Update README file from .md to .adoc file.
This is for the issue https://github.com/almighty/almighty-ui/issues/11

---
This change is [Reviewable](https://reviewable.io/reviews/almighty/almighty-ui/15)

### CODE REVIEW

**Comment by joshuawilson** [comment]
Thanks for the PR.

The change to the Delete button still doesn't make any sense as that css file isn't even read. I have since removed it in an effort to clean up. The buttons should be styled via the PatternFly styles. If you still think it should be changed please create an issue for it. Meanwhile can you please remove that commit from the PR.

Also, can you please squash the merge or better yet just rebase the README changes on top of the latest Master. 

Thank you for you help.

**Comment by gobindaakhuli** [comment]
Done changes please review update.

**Comment by joshuawilson** [comment]
thanks for cleaning it up and sending the PR

**Comment by gobindaakhuli** [comment]
Thank you for merged my PR, are you available on IRC ? or how can I
communicate with you.

**Comment by joshuawilson** [comment]
@gobindaakhuli you can reach me / us on #almighty on freenode

**Pull request merged**
