### PR TITLE
Adding scroll horizontally on work item list view

### PR DESCRIPTION
**Pull request by sanbornsen**
This change is [Reviewable](https://reviewable.io/reviews/almighty/almighty-ui/62)

### CODE REVIEW

**Comment by joshuawilson** [comment]
Why do we want to force a scroll bar to appear even when we don't need it? 

Is there an issue # for this?

@mindreeper2420 Can you please review this?

**Comment by mindreeper2420** [comment]
@joshuawilson @sanbornsen Having a scrollbar appear when it is not necessary gives the false impression of a scrollable interface, which can cause confusion and doubt. The browser should automatically handle any scrollbars (Chrome, IE, Firefox and Edge all handle them differently, including persistent view states).

If the List View is requiring a horizontal scrollbar (as stated here), then it is not sizing properly for the viewport. That should be done in lieu of forcing scrollbars.

Of note, the finalized design will makes this item non-applicable.

**Comment by aslakknutsen** [comment]
Also not having it makes the page jump around moving from page to page. e.g. in demo.almighty.io view the List then go to board and back ... pick your poison I guess.

**Comment by sanbornsen** [comment]
I am sorry. Excuse my limited knowledge in CSS. It should be good now.

**Pull request closed without merging**
