### PR TITLE
Obsidian integration

### PR DESCRIPTION
**Pull request by edewit**
re opened because of faulty rebase

### CODE REVIEW

**Comment by edewit** [comment]
you can test by executing:
```bash
export FORGE_URL=http://generator-backend-obsidian.e8ca.engint.openshiftapps.com/forge
```

**Comment by joshuawilson** [comment]
Thanks @edewit 

[test]

**Comment by joshuawilson** [comment]
@edewit is that link to the backend something we can add to the code so we can deploy this PR to production?

**Comment by joshuawilson** [comment]
@edewit I went ahead and merged this. The UI doesn't break hard, there is just a missing backend. So everything else still works. So I merged it.This will allow you to send updates easier as needed. 

Thanks for the contribution.

**Pull request merged**
