### PR TITLE
Fixed the bug of higlighting WI item from the list

### LINKED ISSUE #422: The 'select' area is larger than 'click to open detail' area
It's possible to click right at the beginning or at the end of the WorkItemList entry and achieve the 'Item' showing as 'selected', but not details being updated.

https://youtu.be/AMv7uMC8_ZM

### PR DESCRIPTION
**Pull request by sanbornsen**
- Clicking extreme edge of a work item list was selecting the item
but not actually opening it.
- fixes #422

### CODE REVIEW

**Comment by aslakknutsen** [comment]
I think this runs the same issue as https://github.com/almighty/almighty-ui/pull/423

The right side work item list entry menu stops working, as the click on the parent takes over.

**Comment by sanbornsen** [comment]
@aslakknutsen Yes I just realized. Let me fix that. Thanks.

**Comment by sanbornsen** [comment]
@nimishamukherjee I tried that, in that case you'll lose out the area around that three dots button. This seemed like a more elegant solution to be. But yeah, you could be right, let's discuss.

**Comment by joshuawilson** [comment]
@nimishamukherjee @sanbornsen I had thought to ask @SMahil to look into adjusting the padding and seeing that would work. It feels like it might be harder but a better solution.

**Comment by joshuawilson** [comment]
@sanbornsen what does adding ng2-dropdown do to solve this issue? Something like that should at least be explained in the description at the top of the PR.

**Comment by sanbornsen** [comment]
@joshua anyway at some point we had to do this for better control over the dropdown directive.

**Comment by joshuawilson** [comment]
@sanbornsen if it doesn't solve the issue then it doesn't belong here. You can make a new issue and do it there. It only confused the solution.

**Comment by sanbornsen** [comment]
@joshuawilson it does solve the issue in a better way.

**Pull request closed without merging**
