### PR TITLE
Upgrade codelyzer dep

### PR DESCRIPTION
**Pull request by ppitonak**
fixes issue #358

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@ppitonak While I'm fine with updating the lib, I don't get the errors you listed in the bug.

**Comment by ppitonak** [comment]
There warnings are not present on jenkins, I'll try to reproduce on Monday

**Comment by joshuawilson** [comment]
The issue has been found to not exist and therefor this change is not needed at this time.

**Pull request closed without merging**
