### PR TITLE
User github Login automation 

### PR DESCRIPTION
**Pull request by naina-verma**
As a end user of ALM , we need to login to alm using github account .
- Added  Page object model for github login Mobile/Desktop
- Added login.spec.js with two login tests with mobile & desktop (For upcoming tests related login too)

### CODE REVIEW

**Comment by joshuawilson** [comment]
@naina-verma this doesn't pass for me when I run it locally.

**Comment by naina-verma** [comment]
@joshuawilson Hi,

I have checked it again , the problem is not with Test cases , the problem is:
- When we click on Sign in with github it does not redirect user to gitbug signin page ,instead it goes to localhost:8088/app/login
You can put this PR on hold i will figure out the solution and update

**Comment by ldimaggi** [comment]
The problem with the test is that by default, the tests access the workitems' UI on localhost at this URL:
 browser.get("http://localhost:8088/?token=justarandomtokenfortest

Redirection to github is not working for login when the tests/server is localhost. I was able to run the login test after making the following code change - but all the other tests (as expected  ;-) then fail.

```
var WorkItemListPage = function () {
//  browser.get("http://localhost:8088/?token=justarandomtokenfortest");
  browser.get("http://demo.almighty.io");
};
```

**Comment by joshuawilson** [comment]
@naina-verma do you plan to fix this or should we close it?

**Comment by naina-verma** [comment]
@joshuawilson , am closing this PR it needs more R&D and changes in code. I will open it later with new changes. 
Thanks

**Pull request closed without merging**
