### PR TITLE
Obsidian

### PR DESCRIPTION
**Pull request by edewit**
@joshuawilson integrated with obsidian-toaster removed a bit duplicate code in 34d0dec

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@edewit when I tried to run it locally I got this error.

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8088' is therefore not allowed access. The response had HTTP status code 404.

Is there something that I need to setup locally to run this?

**Comment by edewit** [comment]
ahh yes, sorry I should have explained that the backend is a separate
project you can find it here:
https://github.com/obsidian-toaster/generator-backend and you can start it
with with `mvn install && java -jar target/generator-swarm.jar`

On Sun, Dec 4, 2016 at 5:57 AM Joshua Wilson <notifications@github.com>
wrote:

@edewit <https://github.com/edewit> when I tried to run it locally I got
this error.

No 'Access-Control-Allow-Origin' header is present on the requested
resource. Origin 'http://localhost:8088' is therefore not allowed access.
The response had HTTP status code 404.

Is there something that I need to setup locally to run this?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/almighty/almighty-ui/pull/414#issuecomment-264684582>,
or mute the thread

**Comment by joshuawilson** [comment]
@edewit is that running someplace so that this will work in Production? Once I merge this PR, it is live in Prod.

**Comment by edewit** [comment]
We don't have anything running atm, maybe we could push a docker image for the code generator under your organisation (example : https://hub.docker.com/r/almightyui/almighty-ui/ ) ?

**Comment by joshuawilson** [comment]
@kbsingh Can you talk with @edewit about hosting his backend?

**Comment by cmoulliard** [comment]
@kbsingh Is it possible that you confirm or not if we can deploy the Front UI of the Code generator in Almighty like also the backend ? We target to deliver a release for Obsidian end of this month and we would like to know if this is doable

**Comment by joshuawilson** [comment]
@cmoulliard that is an interesting idea. But if what @edewit did, is it needed? He made an NPM library that we are importing. So in essence Almighty would be hosting the UI code for the generator. Or am I missing something in the middle?

**Comment by cmoulliard** [comment]
> in the middle?

Nothing was missed. This PR has been created to deploy the Front UI part of the Obsidian code generator (and PR should be updated) but if you could also host our backend part (= another PR to be submitted) on demo.almighty.io, that should be fantastic.
Is demo.almighty.io a static web server, a Node server started as a docker container in OpenShift ?

**Comment by joshuawilson** [comment]
@cmoulliard I work on the UI, for details about hosting and deploying you need to talk to @kbsingh. 

cc: @aslakknutsen @maxandersen

**Comment by joshuawilson** [comment]
@edewit this has rebase issues too.

**Comment by edewit** [comment]
closed in favour of https://github.com/almighty/almighty-ui/pull/462 because I'm super at rebasing

**Pull request closed without merging**
