### PR TITLE
Added page object model page for workitem detail page - intentional i…

### PR DESCRIPTION
**Pull request by ldimaggi**
…n the same module as the work item page as it acts like a child page. Building out the test infrastructure to enable the tests to remain small, easy to read/maintain.

Also - corrected the formatting - using default eclipse indentation.

### CODE REVIEW

**Comment by joshuawilson** [comment]
@ldimaggi I'm getting the following Failure:

A Jasmine spec timed out. Resetting the WebDriver Control Flow.

**Comment by ppitonak** [comment]
@joshuawilson can you whitelist Len so that the Jenkins job starts?

**Comment by joshuawilson** [comment]
@ldimaggi please rebase

**Comment by joshuawilson** [comment]
@ldimaggi It still fails for me. I got the following.

1) Work item board should contain 14 items.
  Message:
    Failed: {"errorMessage":"Element is not currently visible and may not be manipulated","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"27","Content-Type":"application/json; charset=utf-8","Host":"localhost:29592","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_45)"},"httpVersion":"1.1","method":"POST","post":"{\"id\":\":wdc:1475810227204\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/7ce074f0-8c3c-11e6-92ea-dda06741ac3d/element/:wdc:1475810227204/click"}}
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'josh-w541', ip: '192.168.1.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.7.2-101.fc23.x86_64', java.version: '1.8.0_45'
    Driver info: driver.version: unknown

**Comment by michaelkleinhenz** [comment]
Works fine.

**Pull request merged**
