### PR TITLE
Functional tests WI-Type for details page dropdown

### PR DESCRIPTION
**Pull request by naina-verma**
-Verify how many work item type exists in drop down phone/desktop
-Verify the name display of workitem types are correct
-Verfify on selecting workitem it should display in list and detail view both pages phone/desktop

### CODE REVIEW

**Comment by ldimaggi** [comment]
What we want to do is to remove code that is generating warnings such as:

`W/element - more than one element found for locator By(css selector, .wi-type-icon) - the first result will be used`

**Comment by joshuawilson** [comment]
whitelist @naina-verma

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@naina-verma can you please update the code or respond to @ldimaggi

**Comment by naina-verma** [comment]
@joshuawilson , @ldimaggi codeing is in progress , i will update soon!!

**Comment by ldimaggi** [comment]
Comments on the tests failing in the latest commit.

Overall, it looks like the workitem type pulldown implemented in the work item detail page does not behave as expected when the tests are run with PhantomJS in that the tests are not able to locate/access the values in the pulldown. The tests so not encounter these problems when run with FireFox or Chrome. I will open a separate task in github for this problem to be investigated.

In the meantime, we can implement the following workarounds to get the tests running - the updated statements replace the commented-out code:

**In displayAndUpdateWorkItemDetails.spec**

The expected test (the string representation of the work item type) is correctly included in the html, but the test cannot find the corresponding element in the UI when the test is run with PhantomJS:

```
      /* Verify the name display of workitem types are correct  - phone*/
           it('Verify the name display of workitem types are correct ', function() {
              var workItemTitle = "The test workitem title";
              var workItemUpdatedTitle = "The test workitem title - UPDATED";
              page.clickWorkItemQuickAdd();
              page.typeQuickAddWorkItemTitle(workItemTitle);
              page.clickQuickAddSave().then(function() {
                expect(page.workItemTitle(page.firstWorkItem)).toBe(workItemTitle);
                expect(page.workItemTitle(page.firstWorkItem)).toBe(workItemTitle);
                page.workItemViewId(page.workItemByTitle(workItemTitle)).getText().then(function (text) {
                  var detailPage = page.clickWorkItemTitle(page.firstWorkItem, text);
                  detailPage.clickworkItemDetailTypeIcon();
                  var wi_types = ["userstory", "valueproposition", "fundamental","experience","feature","bug"];
                  for(var i=0;i<wi_types.length;i++){
                 // expect(detailPage.WorkItemTypeDropDownList().get(i).getText()).toBe(wi_types[i]);
                  expect(detailPage.workItemTypeDropDownListString(wi_types[i]).getAttribute('innerHTML')).toContain(wi_types[i]);
                  }
                  detailPage.clickWorkItemDetailCloseButton();
                });

              });

      });
```

**Comment by naina-verma** [comment]
@ldimaggi ,
Thanks for the update , i have organized this PR according to your suggested functions.
Its running fine now.
@joshuawilson , this PR is fixed now according to Len's review comments, you can take a look .

**Comment by joshuawilson** [comment]
Thanks @naina-verma I am waiting for @ldimaggi to "approve" it. 
[test]

**Comment by ldimaggi** [comment]
OK - approved to merge. There are some small code "cleanups" needed - but we can address these independently of this merge. The tests are all running now.

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
